[{
  "tcsID": 1111,
  "EmpName": "Gopal",
  "office": "Synergey park",
  "salary" : 600000 
},
{
  "tcsID": 2222,
  "EmpName": "venu",
  "office": "Tidel park",
  "salary" : 600000 
},
{
  "tcsID": 3333,
  "EmpName": "thuluva",
  "office": "solinganalluru",
  "salary" : 600000 
}
]